Don't load Raygun until after `ActionDispatch`
Raygun relies on the `ActionDispatch::DebugExceptions` middleware in
Rails. This change causes Raygun to only insert its middleware after
ActionDispatch is loaded.

This is necessary because recently the load order of Rails appears to
have changed, which means Raygun users on Rails Edge (7.0.0.alpha) may
have been getting a message similar to:

```
NameError: uninitialized constant ActionDispatch::DebugExceptions
```

Originating in `raygun4ruby-3.2.6/lib/raygun/railtie.rb:9:in `block in
<class:Railtie>'`

This change shouldn't affect Rails 5/6, although it
may affect versions 2+ years old as the hook looks like was installed 2
years ago.